options fullstimer;

proc freq data=orion.saleshistory;
	table ordertype;
run;
/*Tasks generate views to limit columns selected from input table*/
PROC SQL;
	CREATE VIEW WORK.SORT AS
		SELECT t.ordertype
			FROM ORION.SALESHISTORY as T
	;
QUIT;

TITLE;
TITLE1 "One-Way Frequencies";
TITLE2 "Results";
FOOTNOTE;
FOOTNOTE1 "Generated by SAS (&_SASSERVERNAME, &SYSSCPL) on %TRIM(%QSYSFUNC(DATE(), NLDATE20.)) at %TRIM(%QSYSFUNC(TIME(), NLTIMAP25.))";

PROC FREQ DATA=WORK.SORT
	ORDER=INTERNAL
;
	TABLES ordertype /  SCORES=TABLE;
RUN;